"""
README 翻訳スクリプト
CI (GitHub Actions) およびローカルテスト (.test/run.sh) から共通利用する。

Usage:
    python3 .github/scripts/translate_readme.py [--input INPUT] [--output OUTPUT]
"""

import argparse
import os
import re

import deepl

# 行ごとスキップするパターン（翻訳せずそのまま出力）
SKIP_PATTERNS = [
    re.compile(r"^```"),              # コードフェンス
    re.compile(r"^<"),               # HTML タグ
    re.compile(r"^\s*$"),            # 空行
    re.compile(r"^!\["),             # 画像行
    re.compile(r"^\[!\["),           # バッジリンク行
    re.compile(r"^https?://"),       # 素の URL
]

# 行頭の markdown 記号（翻訳せず保持する部分）
PREFIX_RE = re.compile(r"^(#{1,6} |\s*[-*+] |\s*\d+\.\s+|\s+)")


def should_skip(line: str) -> bool:
    stripped = line.strip()
    return any(p.match(stripped) for p in SKIP_PATTERNS)


def translate_line(translator: deepl.Translator, line: str) -> str:
    if should_skip(line):
        return line

    # 末尾の改行を退避（Google翻訳が改行を落とすため）
    trailing = "\n" if line.endswith("\n") else ""
    text = line.rstrip("\n")

    # 行頭の記号（## / - / インデント）を分離
    m = PREFIX_RE.match(text)
    prefix = m.group(0) if m else ""
    content = text[len(prefix):]

    if not content.strip():
        return line

    try:
        translated = translator.translate_text(content, source_lang="JA", target_lang="EN-US").text
        result = prefix + (translated if translated else content) + trailing
        return result
    except Exception as e:
        print(f"[WARN] 翻訳失敗: {e!r} | line: {line!r}", flush=True)
        return line


def translate_file(input_path: str, output_path: str) -> None:
    api_key = os.environ.get("DEEPL_API_KEY")
    if not api_key:
        raise EnvironmentError("DEEPL_API_KEY が設定されていません。")
    translator = deepl.Translator(api_key)

    with open(input_path, encoding="utf-8") as f:
        lines = f.readlines()

    in_code_block = False
    output = []
    for line in lines:
        # 言語切替ボタン行（出力ファイルへのリンクを含む行）はスキップ
        if os.path.basename(output_path) in line:
            continue
        if line.strip().startswith("```"):
            in_code_block = not in_code_block
            output.append(line)
            continue
        if in_code_block:
            output.append(line)
        else:
            output.append(translate_line(translator, line))

    header = f'<div align="right"><a href="{input_path}">🇯🇵 日本語</a></div>\n\n'
    footer = f"\n---\n*This file was automatically generated by machine translation from [README.md]({input_path}).*\n"

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(header)
        f.writelines(output)
        f.write(footer)

    print(f"Translated: {input_path} → {output_path}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Translate a Markdown file from Japanese to English.")
    parser.add_argument("--input",  default="README.md",    help="Source file (default: README.md)")
    parser.add_argument("--output", default="README.en.md", help="Output file (default: README.en.md)")
    args = parser.parse_args()
    translate_file(args.input, args.output)


if __name__ == "__main__":
    main()
